platform :ios, '5.0'
xcodeproj 'CarSideBySide'
workspace 'CarSideBySide'
pod 'YISplashScreen', '~> 1.0.0'
pod 'MBFaker', :git => 'git@github.com:juarlex/MBFaker.git'
pod 'NSDate+Helper', '~> 0.0.1'
pod 'NSDate-Extensions', '~> 0.0.1'
pod 'DVCoreDataFinders', '~> 0.4'
pod 'AFIncrementalStore', '~> 0.5.1'
pod 'MBProgressHUD', '~> 0.7'