platform :ios, '5.0'
xcodeproj 'CarSideBySide'
workspace 'CarSideBySide'
pod 'YISplashScreen', '~> 1.0.0'
pod 'MBFaker', :git => 'git@github.com:juarlex/MBFaker.git'
pod 'NSDate+Helper', '~> 0.0.1'
pod 'NSDate-Extensions', '~> 0.0.1'
pod 'DVCoreDataFinders', '~> 0.4'
pod 'AFNetworking', '~> 1.3.2'
pod 'TransformerKit', '~> 0.2.4'
pod 'InflectorKit', '~> 0.0.1'
pod 'MBProgressHUD', '~> 0.7'
pod 'Reachability', '~> 3.1.1'
pod 'AFImageDownloader', '~> 1.0.0'
